name: Build Docker Image and push to Docker Hub, also update associated helm chart

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build . -t alexrsit/nextjsapp:latest
      - name: Push Docker Image
        run: |
          docker login -u alexrsit -p ${{ secrets.DOCKERHUB_PAT }}
          docker push alexrsit/nextjsapp:latest

  update_helm_chart:
    runs-on: ubuntu-latest
    needs: publish_images
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Helm chart with new image tag
        run: |
          sed -i 's|repository: .*|repository: alexrsit/nextjsapp|' ./charts/mychart/values.yaml
          sed -i 's|tag: .*|tag: latest|' ./charts/mychart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./charts/mychart/values.yaml
          git commit -m 'Update Helm chart with new Docker image tag'
          git push origin main
          
