name: Build Docker Image and push to Docker Hub, also update associated helm chart

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build . -t alexrsit/nextjsapp:2.0
      - name: Push Docker Image
        run: |
          docker login -u alexrsit -p ${{ secrets.DOCKERHUB_PAT }}
          docker push alexrsit/nextjsapp:2.0

  update_helm_chart:
    runs-on: ubuntu-latest
    needs: publish_images
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Helm Chart Repository
        run: |
          git clone https://github.com/alexrsit/rosta.dev-helm.git
          cd rosta.dev-helm

      - name: Update Helm chart with new image tag
        run: |
          cd rosta.dev-helm/nextjsapp
          sed -i 's|repository: .*|repository: alexrsit/nextjsapp|' values.yaml
          sed -i 's|tag: .*|tag: 2.0|' values.yaml

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd rosta.dev-helm/nextjsapp
          git config --global user.name 'alexrsit'
          git config --global user.email 'alexander.olander.rosta@regionsormland.se'
          git add values.yaml
          git commit -m 'Update Helm chart with new Docker image tag'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/alexrsit/rosta.dev-helm.git main
          
