name: Build Docker Image and push to Docker Hub, also update associated helm chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  publish_images:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: 1.1.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . -t alexrsit/nextjsapp:${{ env.IMAGE_TAG }}

      - name: Push Docker Image
        run: |
          docker login -u alexrsit -p ${{ secrets.DOCKERHUB_PAT }}
          docker push alexrsit/nextjsapp:${{ env.IMAGE_TAG }}

  update_helm_chart:
    runs-on: ubuntu-latest
    needs: publish_images
    env:
      IMAGE_TAG: ${{ needs.publish_images.outputs.IMAGE_TAG }}
    steps:
      - name: Clone Helm Chart Repository
        run: |
          git clone https://github.com/alexrsit/rosta.dev-helm.git
          ls -la

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Update Helm chart with new image tag
        id: update_values
        run: |
          cd rosta.dev-helm/nextjsapp
          CURRENT_TAG=$(grep 'tag:' values.yaml | awk '{print $2}')
          if [ "$CURRENT_TAG" != "${IMAGE_TAG}" ]; then
            sed -i "s|repository: .*|repository: alexrsit/nextjsapp|" values.yaml
            sed -i "s|tag: .*|tag: ${IMAGE_TAG}|" values.yaml
            echo "UPDATED=true" >> $GITHUB_ENV
          else
            echo "UPDATED=false" >> $GITHUB_ENV
          fi
          cat values.yaml

      - name: Commit and push changes
        if: env.UPDATED == 'true'
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        run: |
          cd rosta.dev-helm/nextjsapp
          git config --global user.name 'alexrsit'
          git config --global user.email 'alexander.olander.rosta@regionsormland.se'
          git add values.yaml
          git commit -m 'Update Helm chart with new Docker image tag'
          git remote set-url origin https://x-access-token:${{ secrets.PAT_GITHUB }}@github.com/alexrsit/rosta.dev-helm.git
          git push origin main